dist: focal
language: python
python:
  - "3.10"
install:
  - pip install -r requirements.txt
  - python manage.py migrate
script:
  - black --check blogging mysite polling || (echo "🔍 Black formatting diff:" && black --diff mysite/urls.py && exit 1)
  - python manage.py test

